### ISSUE TITLE
All responses segfault

### ISSUE THREAD

**Issue by searls** [allan-simon/nihongoparserd#12]
When I build the daemon and run it, every response segfaults. Here is my config: https://github.com/searls/nihongoparserd/commit/78ab0d889a0aeb8e8a99101788ddf598c7afcb34

**Comment by allan-simon** [comment]
Thanks for the dockerrfile, I will try to look into it this weekend, have tried running valgrind on it to have more information on where the segfault come from ?

**Comment by searls** [comment]
We sorted this out if you check the latest (we were missing mecab & the dictionary)
