### ISSUE TITLE
Invalid XML returned when the provided text contains some symbol

### ISSUE THREAD

**Issue by jiru** [allan-simon/nihongoparserd#6]
Commas get parsed into double quotes for some reason, which screws up the XML.

http://127.0.0.1:8842/furigana?str=%2C (%2C is a comma)

Returns:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
<parse>
<token><reading furigana="""><![CDATA[,]]></reading></token>
</parse>
</root>
```
Parenthesis, apostrophe, and some other symbols yet to be determined also trigger the bug.

**Comment by allan-simon** [comment]
the furigana's value  should certainly escaped before being put, I think as of today we simply put it "as it"
